on:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cagix/pandoc-thesis@master
        with:
          srcfile: thesis.md
          targetfile: thesis.pdf
          bibfile: references.bib
          template: eisvogel
      - uses: actions/upload-artifact@v4
        with:
          path: thesis.pdf
          overwrite: true
